service: trellokitty

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  environment:
    JWT_SECRET: "minhaChaveSecreta"
    DATABASE_URL: "postgres://seu_usuario:senha@host/neondb?sslmode=require"

functions:
  api:
    handler: handler.api
    events:
      - http:
          path: "/{proxy+}"
          method: ANY